// This file is automatically generated; do not edit manually.
export const FiltersByDataType = {
  "string": [
    "equal",
    "not equal",
    "is null",
    "is not null"
  ],
  "array": [
    "is empty",
    "is not empty",
    "contains any element where",
    "contains no element where",
    "contains only elements where"
  ]
}
export const ResourceTypes = [
  "Condition",
  "Encounter",
  "Location",
  "MedicationAdministration",
  "Observation",
  "Patient",
  "Procedure",
  "ServiceRequest"
]
export const AttributesByResourceType = {
  "Condition": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "clinicalStatus.coding",
      "type": "array",
      "subpaths": [
        {
          "name": "system",
          "type": "string"
        },
        {
          "name": "code",
          "type": "string"
        },
        {
          "name": "display",
          "type": "string"
        }
      ]
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "encounter.reference",
      "type": "string"
    },
    {
      "name": "onset.datetime",
      "type": "dateTime"
    },
    {
      "name": "code.coding",
      "type": "array",
      "subpaths": [
        {
          "name": "system",
          "type": "string"
        },
        {
          "name": "code",
          "type": "string"
        },
        {
          "name": "display",
          "type": "string"
        }
      ]
    },
    {
      "name": "code.text",
      "type": "string"
    }
  ],
  "Encounter": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "class",
      "type": "array",
      "subpaths": [
        {
          "name": "system",
          "type": "string"
        },
        {
          "name": "code",
          "type": "string"
        },
        {
          "name": "display",
          "type": "string"
        }
      ]
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "location",
      "type": "array",
      "subpaths": [
        {
          "name": "location.reference",
          "type": "string"
        },
        {
          "name": "location.display",
          "type": "string"
        },
        {
          "name": "status",
          "type": "string"
        },
        {
          "name": "period.start",
          "type": "dateTime"
        },
        {
          "name": "period.end",
          "type": "dateTime"
        }
      ]
    },
    {
      "name": "actual.period.start",
      "type": "dateTime"
    },
    {
      "name": "actual.period.end",
      "type": "dateTime"
    }
  ],
  "Location": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "identifier",
      "type": "array",
      "subpaths": [
        {
          "name": "value",
          "type": "string"
        }
      ]
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "form.coding",
      "type": "array",
      "subpaths": [
        {
          "name": "system",
          "type": "string"
        },
        {
          "name": "code",
          "type": "string"
        },
        {
          "name": "display",
          "type": "string"
        }
      ]
    },
    {
      "name": "type",
      "type": "array",
      "subpaths": [
        {
          "name": "coding",
          "type": "array",
          "subpaths": [
            {
              "name": "system",
              "type": "string"
            },
            {
              "name": "code",
              "type": "string"
            },
            {
              "name": "display",
              "type": "string"
            }
          ]
        }
      ]
    },
    {
      "name": "part.of.reference",
      "type": "string"
    }
  ],
  "MedicationAdministration": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "identifier",
      "type": "array",
      "subpaths": [
        {
          "name": "value",
          "type": "string"
        }
      ]
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "encounter.reference",
      "type": "string"
    },
    {
      "name": "request.reference",
      "type": "string"
    },
    {
      "name": "medication.concept.coding",
      "type": "array",
      "subpaths": [
        {
          "name": "system",
          "type": "string"
        },
        {
          "name": "code",
          "type": "string"
        },
        {
          "name": "display",
          "type": "string"
        }
      ]
    },
    {
      "name": "medication.concept.text",
      "type": "string"
    },
    {
      "name": "occurrence.period.start",
      "type": "dateTime"
    },
    {
      "name": "occurrence.period.end",
      "type": "dateTime"
    },
    {
      "name": "dosage.text",
      "type": "string"
    },
    {
      "name": "dosage.route.coding",
      "type": "array",
      "subpaths": [
        {
          "name": "system",
          "type": "string"
        },
        {
          "name": "code",
          "type": "string"
        },
        {
          "name": "display",
          "type": "string"
        }
      ]
    },
    {
      "name": "dosage.route.text",
      "type": "string"
    },
    {
      "name": "dosage.dose.system",
      "type": "string"
    },
    {
      "name": "dosage.dose.unit",
      "type": "string"
    },
    {
      "name": "dosage.dose.code",
      "type": "string"
    },
    {
      "name": "dosage.dose.value",
      "type": "integer"
    },
    {
      "name": "dosage.rateQuantity.system",
      "type": "string"
    },
    {
      "name": "dosage.rateQuantity.unit",
      "type": "string"
    },
    {
      "name": "dosage.rateQuantity.code",
      "type": "string"
    },
    {
      "name": "dosage.rateQuantity.value",
      "type": "integer"
    }
  ],
  "Observation": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "identifier",
      "type": "array",
      "subpaths": [
        {
          "name": "value",
          "type": "string"
        }
      ]
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "category",
      "type": "array",
      "subpaths": [
        {
          "name": "coding",
          "type": "array",
          "subpaths": [
            {
              "name": "system",
              "type": "string"
            },
            {
              "name": "code",
              "type": "string"
            },
            {
              "name": "display",
              "type": "string"
            }
          ]
        }
      ]
    },
    {
      "name": "effective.datetime",
      "type": "dateTime"
    },
    {
      "name": "issued",
      "type": "dateTime"
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "encounter.reference",
      "type": "string"
    },
    {
      "name": "code.coding",
      "type": "array",
      "subpaths": [
        {
          "name": "system",
          "type": "string"
        },
        {
          "name": "code",
          "type": "string"
        },
        {
          "name": "display",
          "type": "string"
        }
      ]
    },
    {
      "name": "code.text",
      "type": "string"
    },
    {
      "name": "value.quantity.value",
      "type": "integer"
    },
    {
      "name": "value.quantity.unit",
      "type": "string"
    },
    {
      "name": "interpretation",
      "type": "array",
      "subpaths": [
        {
          "name": "coding",
          "type": "array",
          "subpaths": [
            {
              "name": "code",
              "type": "string"
            },
            {
              "name": "system",
              "type": "string"
            },
            {
              "name": "display",
              "type": "string"
            }
          ]
        },
        {
          "name": "text",
          "type": "string"
        }
      ]
    },
    {
      "name": "referenceRange",
      "type": "array",
      "subpaths": [
        {
          "name": "text",
          "type": "string"
        }
      ]
    },
    {
      "name": "note",
      "type": "array",
      "subpaths": [
        {
          "name": "text",
          "type": "string"
        }
      ]
    }
  ],
  "Patient": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "gender",
      "type": "string"
    },
    {
      "name": "birth.date",
      "type": "date"
    },
    {
      "name": "deceased.datetime",
      "type": "dateTime"
    },
    {
      "name": "age",
      "type": "integer"
    },
    {
      "name": "isDeceased",
      "type": "boolean"
    }
  ],
  "Procedure": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "encounter.reference",
      "type": "string"
    },
    {
      "name": "basedOn",
      "type": "array",
      "subpaths": [
        {
          "name": "reference",
          "type": "string"
        }
      ]
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "code.coding",
      "type": "array",
      "subpaths": [
        {
          "name": "system",
          "type": "string"
        },
        {
          "name": "code",
          "type": "string"
        },
        {
          "name": "display",
          "type": "string"
        }
      ]
    },
    {
      "name": "code.text",
      "type": "string"
    },
    {
      "name": "occurrencePeriod.start",
      "type": "dateTime"
    },
    {
      "name": "occurrencePeriod.end",
      "type": "dateTime"
    }
  ],
  "ServiceRequest": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "intent",
      "type": "string"
    },
    {
      "name": "authoredOn",
      "type": "dateTime"
    },
    {
      "name": "occurrence.datetime",
      "type": "dateTime"
    },
    {
      "name": "priority",
      "type": "string"
    }
  ]
};
export const FlatAttributesByResourceType = {
  "Condition": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "clinicalStatus.coding.system",
      "type": "string"
    },
    {
      "name": "clinicalStatus.coding.code",
      "type": "string"
    },
    {
      "name": "clinicalStatus.coding.display",
      "type": "string"
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "encounter.reference",
      "type": "string"
    },
    {
      "name": "onset.datetime",
      "type": "dateTime"
    },
    {
      "name": "code.coding.system",
      "type": "string"
    },
    {
      "name": "code.coding.code",
      "type": "string"
    },
    {
      "name": "code.coding.display",
      "type": "string"
    },
    {
      "name": "code.text",
      "type": "string"
    }
  ],
  "Encounter": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "class.system",
      "type": "string"
    },
    {
      "name": "class.code",
      "type": "string"
    },
    {
      "name": "class.display",
      "type": "string"
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "location.location.reference",
      "type": "string"
    },
    {
      "name": "location.location.display",
      "type": "string"
    },
    {
      "name": "location.status",
      "type": "string"
    },
    {
      "name": "location.period.start",
      "type": "dateTime"
    },
    {
      "name": "location.period.end",
      "type": "dateTime"
    },
    {
      "name": "actual.period.start",
      "type": "dateTime"
    },
    {
      "name": "actual.period.end",
      "type": "dateTime"
    }
  ],
  "Location": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "identifier.value",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "form.coding.system",
      "type": "string"
    },
    {
      "name": "form.coding.code",
      "type": "string"
    },
    {
      "name": "form.coding.display",
      "type": "string"
    },
    {
      "name": "type.coding.system",
      "type": "string"
    },
    {
      "name": "type.coding.code",
      "type": "string"
    },
    {
      "name": "type.coding.display",
      "type": "string"
    },
    {
      "name": "part.of.reference",
      "type": "string"
    }
  ],
  "MedicationAdministration": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "identifier.value",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "encounter.reference",
      "type": "string"
    },
    {
      "name": "request.reference",
      "type": "string"
    },
    {
      "name": "medication.concept.coding.system",
      "type": "string"
    },
    {
      "name": "medication.concept.coding.code",
      "type": "string"
    },
    {
      "name": "medication.concept.coding.display",
      "type": "string"
    },
    {
      "name": "medication.concept.text",
      "type": "string"
    },
    {
      "name": "occurrence.period.start",
      "type": "dateTime"
    },
    {
      "name": "occurrence.period.end",
      "type": "dateTime"
    },
    {
      "name": "dosage.text",
      "type": "string"
    },
    {
      "name": "dosage.route.coding.system",
      "type": "string"
    },
    {
      "name": "dosage.route.coding.code",
      "type": "string"
    },
    {
      "name": "dosage.route.coding.display",
      "type": "string"
    },
    {
      "name": "dosage.route.text",
      "type": "string"
    },
    {
      "name": "dosage.dose.system",
      "type": "string"
    },
    {
      "name": "dosage.dose.unit",
      "type": "string"
    },
    {
      "name": "dosage.dose.code",
      "type": "string"
    },
    {
      "name": "dosage.dose.value",
      "type": "integer"
    },
    {
      "name": "dosage.rateQuantity.system",
      "type": "string"
    },
    {
      "name": "dosage.rateQuantity.unit",
      "type": "string"
    },
    {
      "name": "dosage.rateQuantity.code",
      "type": "string"
    },
    {
      "name": "dosage.rateQuantity.value",
      "type": "integer"
    }
  ],
  "Observation": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "identifier.value",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "category.coding.system",
      "type": "string"
    },
    {
      "name": "category.coding.code",
      "type": "string"
    },
    {
      "name": "category.coding.display",
      "type": "string"
    },
    {
      "name": "effective.datetime",
      "type": "dateTime"
    },
    {
      "name": "issued",
      "type": "dateTime"
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "encounter.reference",
      "type": "string"
    },
    {
      "name": "code.coding.system",
      "type": "string"
    },
    {
      "name": "code.coding.code",
      "type": "string"
    },
    {
      "name": "code.coding.display",
      "type": "string"
    },
    {
      "name": "code.text",
      "type": "string"
    },
    {
      "name": "value.quantity.value",
      "type": "integer"
    },
    {
      "name": "value.quantity.unit",
      "type": "string"
    },
    {
      "name": "interpretation.coding.code",
      "type": "string"
    },
    {
      "name": "interpretation.coding.system",
      "type": "string"
    },
    {
      "name": "interpretation.coding.display",
      "type": "string"
    },
    {
      "name": "interpretation.text",
      "type": "string"
    },
    {
      "name": "referenceRange.text",
      "type": "string"
    },
    {
      "name": "note.text",
      "type": "string"
    }
  ],
  "Patient": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "patient_id",
      "type": "string"
    },
    {
      "name": "gender",
      "type": "string"
    },
    {
      "name": "birth.date",
      "type": "date"
    },
    {
      "name": "deceased.datetime",
      "type": "dateTime"
    },
    {
      "name": "age",
      "type": "integer"
    },
    {
      "name": "isDeceased",
      "type": "boolean"
    }
  ],
  "Procedure": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "encounter.reference",
      "type": "string"
    },
    {
      "name": "basedOn.reference",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "code.coding.system",
      "type": "string"
    },
    {
      "name": "code.coding.code",
      "type": "string"
    },
    {
      "name": "code.coding.display",
      "type": "string"
    },
    {
      "name": "code.text",
      "type": "string"
    },
    {
      "name": "occurrencePeriod.start",
      "type": "dateTime"
    },
    {
      "name": "occurrencePeriod.end",
      "type": "dateTime"
    }
  ],
  "ServiceRequest": [
    {
      "name": "resourceType",
      "type": "string"
    },
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "subject.reference",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "intent",
      "type": "string"
    },
    {
      "name": "authoredOn",
      "type": "dateTime"
    },
    {
      "name": "occurrence.datetime",
      "type": "dateTime"
    },
    {
      "name": "priority",
      "type": "string"
    }
  ]
};
